// Generated by Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import SafariServices;
@import UIKit;
@import UserNotifications;
@import WebKit;
#endif

#import <Capacitor/Capacitor.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Capacitor",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class CAPBridge;

SWIFT_CLASS_NAMED("CAPAccessibilityPlugin")
@interface CAPAccessibilityPlugin : CAPPlugin
- (void)load;
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPAppPlugin")
@interface CAPAppPlugin : CAPPlugin
- (void)load;
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPBackgroundTaskPlugin")
@interface CAPBackgroundTaskPlugin : CAPPlugin
- (void)load;
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIViewController;
@class CAPConfig;
@class CAPPluginCall;
@class WKWebView;

SWIFT_CLASS("_TtC9Capacitor9CAPBridge")
@interface CAPBridge : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSNotification * _Nonnull statusBarTappedNotification;)
+ (NSNotification * _Nonnull)statusBarTappedNotification SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSNotification * _Nonnull tmpVCAppeared;)
+ (NSNotification * _Nonnull)tmpVCAppeared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) UIViewController * _Nonnull viewController;
@property (nonatomic, strong) CAPConfig * _Nonnull config;
- (CAPPluginCall * _Nullable)getSavedCall:(NSString * _Nonnull)callbackId SWIFT_WARN_UNUSED_RESULT;
- (void)releaseCall:(CAPPluginCall * _Nonnull)call;
- (void)releaseCallWithCallbackId:(NSString * _Nonnull)callbackId;
/// Eval JS for a specific plugin.
- (void)evalWithPlugin:(CAPPlugin * _Nonnull)plugin js:(NSString * _Nonnull)js;
/// Eval JS in the web view
- (void)evalWithJs:(NSString * _Nonnull)js;
- (void)triggerJSEventWithEventName:(NSString * _Nonnull)eventName target:(NSString * _Nonnull)target;
- (void)triggerJSEventWithEventName:(NSString * _Nonnull)eventName target:(NSString * _Nonnull)target data:(NSString * _Nonnull)data;
- (void)triggerWindowJSEventWithEventName:(NSString * _Nonnull)eventName;
- (void)triggerWindowJSEventWithEventName:(NSString * _Nonnull)eventName data:(NSString * _Nonnull)data;
- (void)triggerDocumentJSEventWithEventName:(NSString * _Nonnull)eventName;
- (void)triggerDocumentJSEventWithEventName:(NSString * _Nonnull)eventName data:(NSString * _Nonnull)data;
- (WKWebView * _Nullable)getWebView SWIFT_WARN_UNUSED_RESULT;
- (void)presentVC:(UIViewController * _Nonnull)viewControllerToPresent animated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)dismissVCWithAnimated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class WKNavigation;
@class WKNavigationAction;
@class WKUserContentController;
@class WKScriptMessage;
@class WKFrameInfo;
@class WKWebViewConfiguration;
@class WKWindowFeatures;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC9Capacitor23CAPBridgeViewController")
@interface CAPBridgeViewController : UIViewController <WKNavigationDelegate, WKScriptMessageHandler, WKUIDelegate>
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull supportedOrientations;
@property (nonatomic, copy) NSString * _Nonnull startDir;
@property (nonatomic, copy) NSString * _Nullable config;
- (void)loadView;
- (void)viewDidLoad;
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webViewWebContentProcessDidTerminate:(WKWebView * _Nonnull)webView;
- (BOOL)canPerformUnwindSegueAction:(SEL _Nonnull)action fromViewController:(UIViewController * _Nonnull)fromViewController withSender:(id _Nonnull)sender SWIFT_WARN_UNUSED_RESULT;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (void)didReceiveMemoryWarning;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@property (nonatomic, readonly) UIStatusBarAnimation preferredStatusBarUpdateAnimation;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptTextInputPanelWithPrompt:(NSString * _Nonnull)prompt defaultText:(NSString * _Nullable)defaultText initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(NSString * _Nullable))completionHandler;
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) UIInterfaceOrientation preferredInterfaceOrientationForPresentation;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class SFSafariViewController;

SWIFT_CLASS_NAMED("CAPBrowserPlugin")
@interface CAPBrowserPlugin : CAPPlugin <SFSafariViewControllerDelegate>
- (void)safariViewControllerDidFinish:(SFSafariViewController * _Nonnull)controller;
- (void)safariViewController:(SFSafariViewController * _Nonnull)controller didCompleteInitialLoad:(BOOL)didLoadSuccessfully;
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImagePickerController;
@class UIPopoverPresentationController;

SWIFT_CLASS_NAMED("CAPCameraPlugin")
@interface CAPCameraPlugin : CAPPlugin <UIImagePickerControllerDelegate, UINavigationControllerDelegate, UIPopoverPresentationControllerDelegate>
- (void)imagePickerControllerDidCancel:(UIImagePickerController * _Nonnull)picker;
- (void)popoverPresentationControllerDidDismissPopover:(UIPopoverPresentationController * _Nonnull)popoverPresentationController;
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPClipboardPlugin")
@interface CAPClipboardPlugin : CAPPlugin
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9Capacitor9CAPConfig")
@interface CAPConfig : NSObject
/// Get the value of a configuration option for a specific plugin.
- (id _Nullable)getPluginConfigValue:(NSString * _Nonnull)pluginId :(NSString * _Nonnull)configKey SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)getValue:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getString:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("CAPConsolePlugin")
@interface CAPConsolePlugin : CAPPlugin
- (void)log:(CAPPluginCall * _Nonnull)call;
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPDevicePlugin")
@interface CAPDevicePlugin : CAPPlugin
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// CAPFileManager helps map file schemes to physical files, whether they are on
/// disk, in a bundle, or in another location.
SWIFT_CLASS("_TtC9Capacitor14CAPFileManager")
@interface CAPFileManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPFilesystemPlugin")
@interface CAPFilesystemPlugin : CAPPlugin
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPGeolocationPlugin")
@interface CAPGeolocationPlugin : CAPPlugin
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPHapticsPlugin")
@interface CAPHapticsPlugin : CAPPlugin
- (void)impact:(CAPPluginCall * _Nonnull)call;
- (void)notification:(CAPPluginCall * _Nonnull)call;
- (void)selectionStart:(CAPPluginCall * _Nonnull)call;
- (void)selectionChanged:(CAPPluginCall * _Nonnull)call;
- (void)selectionEnd:(CAPPluginCall * _Nonnull)call;
- (void)vibrate:(CAPPluginCall * _Nonnull)call;
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Implement three common modal types: alert, confirm, and prompt
SWIFT_CLASS_NAMED("CAPLocalNotificationsPlugin")
@interface CAPLocalNotificationsPlugin : CAPPlugin
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Implement three common modal types: alert, confirm, and prompt
SWIFT_CLASS_NAMED("CAPModalsPlugin")
@interface CAPModalsPlugin : CAPPlugin
- (void)alert:(CAPPluginCall * _Nonnull)call;
- (void)confirm:(CAPPluginCall * _Nonnull)call;
- (void)prompt:(CAPPluginCall * _Nonnull)call;
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPNetworkPlugin")
@interface CAPNetworkPlugin : CAPPlugin
- (void)load;
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Notificaton types for NSNotificationCenter
typedef SWIFT_ENUM(NSInteger, CAPNotifications, closed) {
  CAPNotificationsURLOpen = 0,
  CAPNotificationsUniversalLinkOpen = 1,
  CAPNotificationsContinueActivity = 2,
  CAPNotificationsDidRegisterForRemoteNotificationsWithDeviceToken = 3,
  CAPNotificationsDidFailToRegisterForRemoteNotificationsWithError = 4,
  CAPNotificationsDecidePolicyForNavigationAction = 5,
};


/// Allow to check hardware permissions
SWIFT_CLASS_NAMED("CAPPermissionsPlugin")
@interface CAPPermissionsPlugin : CAPPlugin
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPPhotosPlugin")
@interface CAPPhotosPlugin : CAPPlugin
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface CAPPluginCall (SWIFT_EXTENSION(Capacitor))
- (NSString * _Nullable)getString:(NSString * _Nonnull)key :(NSString * _Nullable)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (NSDate * _Nullable)getDate:(NSString * _Nonnull)key :(NSDate * _Nullable)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nullable)getObject:(NSString * _Nonnull)key defaultValue:(NSDictionary<NSString *, id> * _Nullable)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasOption:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)success;
- (void)success:(NSDictionary<NSString *, id> * _Nonnull)data;
- (void)resolve;
- (void)resolve:(NSDictionary<NSString *, id> * _Nonnull)data;
- (void)error:(NSString * _Nonnull)message :(NSError * _Nullable)error :(NSDictionary<NSString *, id> * _Nonnull)data;
- (void)reject:(NSString * _Nonnull)message :(NSString * _Nullable)code :(NSError * _Nullable)error :(NSDictionary<NSString *, id> * _Nonnull)data;
- (void)unimplemented;
@end

@class NSNotification;

/// Implement three common modal types: alert, confirm, and prompt
SWIFT_CLASS_NAMED("CAPPushNotificationsPlugin")
@interface CAPPushNotificationsPlugin : CAPPlugin
- (void)load;
- (void)didRegisterForRemoteNotificationsWithDeviceTokenWithNotification:(NSNotification * _Nonnull)notification;
- (void)didFailToRegisterForRemoteNotificationsWithErrorWithNotification:(NSNotification * _Nonnull)notification;
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Implement three common modal types: alert, confirm, and prompt
SWIFT_CLASS_NAMED("CAPSharePlugin")
@interface CAPSharePlugin : CAPPlugin
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPSplashScreenPlugin")
@interface CAPSplashScreenPlugin : CAPPlugin
- (void)load;
- (void)show:(CAPPluginCall * _Nonnull)call;
- (void)hide:(CAPPluginCall * _Nonnull)call;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)_ context:(void * _Nullable)context;
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// StatusBar plugin. Requires “View controller-based status bar appearance” to
/// be “YES” in Info.plist
SWIFT_CLASS_NAMED("CAPStatusBarPlugin")
@interface CAPStatusBarPlugin : CAPPlugin
- (void)load;
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Storage Plugin
SWIFT_CLASS_NAMED("CAPStoragePlugin")
@interface CAPStoragePlugin : CAPPlugin
- (void)load;
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPToastPlugin")
@interface CAPToastPlugin : CAPPlugin
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UNUserNotificationCenter;
@class UNNotification;
@class UNNotificationResponse;

SWIFT_CLASS("_TtC9Capacitor35CAPUNUserNotificationCenterDelegate")
@interface CAPUNUserNotificationCenterDelegate : NSObject <UNUserNotificationCenterDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Handle delegate willPresent action when the app is in the foreground.
/// This controls how a notification is presented when the app is running, such as
/// whether it should stay silent, display a badge, play a sound, or show an alert.
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center willPresentNotification:(UNNotification * _Nonnull)notification withCompletionHandler:(void (^ _Nonnull)(UNNotificationPresentationOptions))completionHandler;
/// Handle didReceive action, called when a notification opens or activates
/// the app based on an action.
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center didReceiveNotificationResponse:(UNNotificationResponse * _Nonnull)response withCompletionHandler:(void (^ _Nonnull)(void))completionHandler;
@end


SWIFT_CLASS_NAMED("CAPWebViewPlugin")
@interface CAPWebViewPlugin : CAPPlugin
- (null_unspecified instancetype)initWithBridge:(CAPBridge * _Null_unspecified)bridge pluginId:(NSString * _Null_unspecified)pluginId pluginName:(NSString * _Null_unspecified)pluginName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface UILabel (SWIFT_EXTENSION(Capacitor))
- (void)drawRect:(CGRect)rect;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
